[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "12.17.0", NODE_ENV = "production" }

[dev]
  command = "npm start"
  publish = "dist"
  port = 3000
  targetPort = 8080
  framework = "#custom"
  NODE_ENV = "development"
