name: dispatch update

on: repository_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Exit if dispatch is not 'update'
        if: github.event.action != 'update'
        run: echo 'up-to-date'

      - name: Update
        run: echo 'updating'
